# Site settings
url  : http://bigpigeon.github.io
title: bigpigeon
email: bigpigeon0@gmail.com
description: bigpigeon的博客
timezone: Asia/Shanghai
play_bridge: //ec2-52-192-136-101.ap-northeast-1.compute.amazonaws.com:9090/bridge
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  bigpigeon
permalink: /:year/:month/:day/:title/

# Build settings
markdown: redcarpet

collections:
  demo_posts:
    output: ture
    permalink: /demo_posts/:path/

defaults:
  -
    scope:
      path: "demo_posts"
      type: "demos"
    values:
      layout: "demo"


# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
