version: '2'
services:
  generate:
    image: bigpigeon0/blog_temp
    build: docker/hugo
    volumes:
      - .:/data
    working_dir: /data
    command: hugo -b https://bigpigeon.org
  sandbox:
    image: sandbox
    build: playground/sandbox
    command: sandbox
    restart: always
    ports:
      - 127.0.0.1:8080:8080
