version: '2'
services:
  generate:
    image: bigpigeon0/blog_temp
    build: docker/hugo
    volumes:
      - .:/data
    working_dir: /data
    command: hugo -b http://bigpigeon.org -d /var/www/html
  sandbox:
    image: sandbox
    command: sandbox
    restart: always
  nginx:
    image: bigpigeon0/blog_ngx
    build: docker/nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/temp
      - /var/www:/var/www
    volumes_from:
      - generate
    links:
      - sandbox:sandbox
    environment:
      - NGINX_PORT=80
      - NGINX_PORT_SSL=443
    command: /bin/bash -c "envsubst < /etc/nginx/temp/default.temp > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - sandbox
    restart: always

