version: '2'
services:
  nginx:
    image: bigpigeon0/blog_ngx
    build: docker/nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/temp
      - /var/www/ssl:/var/www/ssl
      - /var/www/.well-known:/var/www/.well-known
    volumes_from:
      - generate
    links:
      - sandbox:sandbox
    environment:
      - NGINX_PORT=80
      - NGINX_PORT_SSL=443
      - DOMAIN=bigpigeon.org
    command: /bin/bash -c "envsubst < /etc/nginx/temp/default.temp > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - sandbox
    restart: always
  generate:
    command: hugo -b https://bigpigeon.org -d /var/www/html
